"""Fresh start

Revision ID: 1e80db13ec72
Revises: 999c84e4cb17
Create Date: 2025-05-24 15:46:28.758730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e80db13ec72'
down_revision = '999c84e4cb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_type', sa.String(length=20), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('profile_picture_type')
        batch_op.drop_column('profile_picture_data')

    # ### end Alembic commands ###
